### ISSUE TITLE
Design: Cover img

### ISSUE THREAD

**Issue by Kedrigern** [Kedrigern/Kedrigern.github.io#1]
Přemýšlel jsem jak vylepšit cover image.

- vynechal bych "Pirátský poslanec"
- namísto toho bych tam dal tag cloud (opendata, opensource, open access, big data, piráti, svoboda, kyberbezpečnost, cyklo, eu, praha, doprava, sněmovna, poslanec)
- logo Pirátská strana by mohla být součástí toho cloudu, anebo zůstat - dle toho jak to bude vypadat

**Comment by matejsoukup** [comment]
Zkusil jsem to nějak nahodit, nejsem s tím ještě úplně spokojený, Nějaký nápady?

**Comment by Kedrigern** [comment]
Myslím si, že je to dobrý směr. Máš někde editovatelnou verzi?

**Comment by matejsoukup** [comment]
Jak cloud, tak původní bílý cover (cover__.jpg) je v assets/img. Cloud jsem dělal přes https://worditout.com , myslím, že je potřeba znova vygenerovat, jestli ho chceme měnit (nejde jednoduše editovat).
