### ISSUE TITLE
dvouslopcové vs jednosloupové

### ISSUE THREAD

**Issue by jitka** [Kedrigern/Kedrigern.github.io#10]
Když na notebooku 1600x900 pustím chromium na levé půlce displaye tak má blog stále dva sloupce, ale ten pravý je už na hranici čitelnosti, možna by to chtělo přepínat na jednoslopcové dřiv.
U hraničních šířek je příliš velká mezera mezi sloupci možná bude nejlepši udělat aby ta mezera byla dynamická podle šířky stránky a tj i šířky okrajů.

**Comment by matejsoukup** [comment]
Zkusil jsem dát jedno sloupcové už u středních šířek obrazovky. Mezera je teď je dělaná tak, že je to vždy 1/12 celku. Možná by naopak pomohlo kdyby byla pevná.
