### ISSUE TITLE
Kategorie s diakritikou

### ISSUE THREAD

**Issue by Kedrigern** [Kedrigern/Kedrigern.github.io#18]
V současnosti u kategorii používáme diakritiku a zároveň je kategorie užita v url.

Funguje to, ale dělá to nepěkné url a asi to není úplně nejšťastnější řešení.

Osobně by se mi líbilo, kdybych v url odstraňovali diaktiriku. Ale problém by zas byl s existujícími odkazy. Jelikož hostujeme přímo u githubu, tak nemůžeme jen tak udělat nginx redirecty. 

Co s tím?

**Comment by matejsoukup** [comment]
Žádné 100% řešení mě nenapadá. Osobně jsem pro úplně kategorii z URL vyloučit. U stávajících postů pak můžeme nastavit permalink ručně na stávající.

**Comment by Kedrigern** [comment]
OK, takže:

1. Otestuj redirecty v našem prostředí 
2. Z nové url bych tedy asi vyhodil kategorie
3. Možná bych vychodil nebo výrazně zjednodušil datum (třeba bych tam nechal jen rok)

**Comment by matejsoukup** [comment]
Kategorie budeme psát striktně s diakritikou kvůli hezkému výpisu článků podle kategorií. Naopak byla kategorie vypuštěna z URL - na dosavadní posty zřízeny redirekty (přímo v postech). Z datumu zbyl jenom rok.
