### ISSUE TITLE
rozbité formátování v bio

### ISSUE THREAD

**Issue by HaruhiAnon** [Kedrigern/Kedrigern.github.io#26]
V https://www.profant.eu/bio/ je rozbité formátování textu (viz přiložený screen, zobrazeno ve Firefoxu).
![tmwyjkiclgbnrkadymldjqat](https://user-images.githubusercontent.com/9403119/41656208-7e01c3c4-748f-11e8-8045-81c423e19edf.png)

**Comment by Kedrigern** [comment]
Fixed
