### ISSUE TITLE
Kategorie

### ISSUE THREAD

**Issue by Kedrigern** [Kedrigern/Kedrigern.github.io#4]
V současnosti nebudeme kategorie řešit.

Kategorie budou přibližně tyto:

- opendata
- e-government
- sněmovna / politika 
- cyklistika
- ostatní

Ale začal bych to řešit až, když budeme mít více článků.

**Comment by matejsoukup** [comment]
Zatím jsem je zakomentoval, až toho bude víc, doděláme.

**Comment by Kedrigern** [comment]
Hele tak už máme dost článků. Nejjednodušší mi přijde:

1. Udělat stránku, kde je vždy kategorie a pod ní dané články
2. Odkazy pak povedou na ten konkrétní nadpis

Tím se zbavíme problému s přibýváním kategorii apod. 

Obdobně je to řešeno na pirati.cz: https://www.pirati.cz/tags/#slu%C5%BEebn%C3%AD-z%C3%A1kon , ale tady počítáme méně článků, čili bych klidně udělal atraktivnější výpis. Třeba by kategorie mohli být rozklikávací a rozbalená by byla vždy jen ta aktuální.

**Comment by matejsoukup** [comment]
Takže v podstatě to co už je (https://www.profant.eu/categories/), jen trochu hezčí a dát na to někde odkaz?

**Comment by Kedrigern** [comment]
Ano, redesign této stránky. Dal bych to zatím klikací v tag cloudu na úvodní stránce.

**Comment by matejsoukup** [comment]
Základní zformátování stránky + hozen odkaz na tag cloud
