### ISSUE TITLE
Výpis článků

### ISSUE THREAD

**Issue by Kedrigern** [Kedrigern/Kedrigern.github.io#6]
Na titulní stránce by to chtělo vylepšit výpis článků. Perex by mohl být vedle fotky (když nemá širokoúhlý formát). 

Stejně tak pod odkazem Zápisky vpravo v rohu má být výpis článků.

**Comment by matejsoukup** [comment]
Jaký bude tedy rozdíl mezi Zápisky a indexem?

**Comment by Kedrigern** [comment]
Asi nemusí být žádný, zvláště ne teď.
